module.exports = [ { id: 5066,
    name: 'Section 1',
    visible: 1,
    summary: '<p>This is an amazing summary, written in HTML</p>',
    summaryformat: 1,
    modules: 
     [ { id: 17005,
         url: 'https://moodle.example.com/mod/url/view.php?id=17005',
         name: 'Link Module',
         instance: 1095,
         description: '<div class="no-overflow"><p>Description of Link Module</p></div>',
         visible: 1,
         modicon: 'https://moodle.example.com/theme/image.php/_s/more/url/1455119128/icon',
         modname: 'url',
         modplural: 'Links/URLs',
         indent: 0,
         contents: 
          [ { type: 'url',
              filename: 'Link Module',
              filepath: null,
              filesize: 0,
              fileurl: 'https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg',
              timecreated: null,
              timemodified: 1455055470,
              sortorder: null,
              userid: null,
              author: null,
              license: null } ] },
       { id: 17006,
         url: 'https://moodle.example.com/mod/page/view.php?id=17006',
         name: 'Page Module',
         instance: 805,
         description: '<div class="no-overflow"><p>Description of this amazing page</p></div>',
         visible: 1,
         modicon: 'https://moodle.example.com/theme/image.php/_s/more/page/1455119128/icon',
         modname: 'page',
         modplural: 'Textseiten',
         indent: 0,
         contents: 
          [ { type: 'file',
              filename: 'index.html',
              filepath: '/',
              filesize: 0,
              fileurl: 'https://moodle.example.com/webservice/pluginfile.php/32734/mod_page/content/index.html?forcedownload=1',
              timecreated: null,
              timemodified: 1455034393,
              sortorder: 1,
              userid: null,
              author: null,
              license: null } ] },
       { id: 17010,
         url: 'https://moodle.example.com/mod/forum/view.php?id=17010',
         name: 'Forum Module',
         instance: 874,
         description: '<div class="no-overflow"><p>Description of this fabulous forum</p></div>',
         visible: 1,
         modicon: 'https://moodle.example.com/theme/image.php/_s/more/forum/1455119128/icon',
         modname: 'forum',
         modplural: 'Foren',
         indent: 0 },
        ] },
  { id: 5067,
    name: 'Section 2',
    visible: 1,
    summary: '',
    summaryformat: 1,
    modules: 
     [ { id: 16100,
         name: 'Label Module',
         instance: 1060,
         description: '<div class="no-overflow"><p><strong>Labeling</strong></p></div>',
         visible: 1,
         modicon: 'https://moodle.example.com/theme/image.php/_s/more/label/1455119128/icon',
         modname: 'label',
         modplural: 'Textfelder',
         indent: 0 },
       { id: 16938,
         url: 'https://moodle.example.com/mod/resource/view.php?id=16938',
         name: 'File Module',
         instance: 7744,
         visible: 1,
         modicon: 'https://moodle.example.com/theme/image.php/_s/more/core/1455119128/f/pdf-24',
         modname: 'resource',
         modplural: 'Dateien',
         indent: 0,
         contents: 
          [ { type: 'file',
              filename: 'How-To-Bake-Brownies.pdf',
              filepath: '/',
              filesize: 2802498,
              fileurl: 'https://moodle.example.com/webservice/pluginfile.php/32489/mod_resource/content/1/Brownies.pdf?forcedownload=1',
              timecreated: 1454859657,
              timemodified: 1454859660,
              sortorder: 1,
              userid: 4763,
              author: '',
              license: 'allrightsreserved' } ] },
       { id: 3004,
         name: 'Folder Module',
         instance: 161,
         visible: 1,
         modicon: 'https://moodle.example.com/theme/image.php/_s/more/folder/1455119128/icon',
         modname: 'folder',
         modplural: 'Verzeichnisse',
         indent: 0,
         contents: 
          [ { type: 'file',
              filename: 'file1.pdf',
              filepath: '/',
              filesize: 2729094,
              fileurl: 'https://moodle.example.com/webservice/pluginfile.php/5169/mod_folder/content/36/aufgabensammlung.pdf?forcedownload=1',
              timecreated: 1369641150,
              timemodified: 1452180577,
              sortorder: 0,
              userid: 176,
              author: '',
              license: 'cc' },
            { type: 'file',
              filename: 'file2.pdf',
              filepath: '/',
              filesize: 2213616,
              fileurl: 'https://moodle.example.com/webservice/pluginfile.php/5169/mod_folder/content/36/skript.pdf?forcedownload=1',
              timecreated: 1387209002,
              timemodified: 1452000495,
              sortorder: 0,
              userid: 176,
              author: '',
              license: 'cc' } ] },
        ] } ];
